version: 2.1

orbs:
  ci-caching: jobcloud/ci-caching@3.1.1
  ci-php: jobcloud/ci-php@2.4.0

workflows:
  version: 2
  test-php-kafka-schema-registry-client:
    jobs:
      - ci-caching/build-docker-images
      - ci-php/install-dependencies:
          requires:
            - ci-caching/build-docker-images
      - ci-php/coverage:
          requires:
            - ci-php/install-dependencies
      - ci-php/code-style:
          requires:
            - ci-php/install-dependencies
      - ci-php/static-analysis:
          requires:
            - ci-php/install-dependencies
      - ci-php/infection-testing:
          requires:
            - ci-php/install-dependencies
