version: 2.1

parameters:
  dockerComposeFile:
    type: string
    default: "./docker/docker-compose.yml"
  dependencyCheckSumFile:
    type: string
    default: "./composer.json"

orbs:
  ci-caching: jobcloud/ci-caching@0.5
  ci-php: jobcloud/ci-php@0.3

workflows:
  php-kafka-schema-registry-client:
    jobs:
      - ci-caching/build-docker-images:
          dockerComposeFile: << pipeline.parameters.dockerComposeFile >>
      - ci-php/install-dependencies:
          dockerComposeFile: << pipeline.parameters.dockerComposeFile >>
          dependencyCheckSumFile: << pipeline.parameters.dependencyCheckSumFile >>
          requires:
            - ci-caching/build-docker-images
      - ci-php/coverage:
          dockerComposeFile: << pipeline.parameters.dockerComposeFile >>
          dependencyCheckSumFile: << pipeline.parameters.dependencyCheckSumFile >>
          requires:
            - ci-php/install-dependencies
      - ci-php/code-style:
          dockerComposeFile: << pipeline.parameters.dockerComposeFile >>
          dependencyCheckSumFile: << pipeline.parameters.dependencyCheckSumFile >>
          requires:
            - ci-php/install-dependencies
      - ci-php/static-analysis:
          dockerComposeFile: << pipeline.parameters.dockerComposeFile >>
          dependencyCheckSumFile: << pipeline.parameters.dependencyCheckSumFile >>
          requires:
            - ci-php/install-dependencies
      - ci-php/infection-testing:
          dockerComposeFile: << pipeline.parameters.dockerComposeFile >>
          dependencyCheckSumFile: << pipeline.parameters.dependencyCheckSumFile >>
          requires:
            - ci-php/install-dependencies