version: 2.1

orbs:
  ci-caching: jobcloud/ci-caching@2.1.0
  ci-php: jobcloud/ci-php@1.1.0

workflows:
  php-kafka-schema-registry-client:
    jobs:
      - ci-caching/build-docker-images:
          dockerComposeFile: "./docker/docker-compose.yml"
          additionalCacheKey: "v2"
      - ci-php/install-dependencies:
          dockerComposeFile: "./docker/docker-compose.yml"
          dockerAdditionalCacheKey: "v2"
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-caching/build-docker-images
      - ci-php/coverage:
          dockerComposeFile: "./docker/docker-compose.yml"
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-php/install-dependencies
      - ci-php/code-style:
          dockerComposeFile: "./docker/docker-compose.yml"
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-php/install-dependencies
      - ci-php/static-analysis:
          dockerComposeFile: "./docker/docker-compose.yml"
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-php/install-dependencies
      - ci-php/infection-testing:
          dockerComposeFile: "./docker/docker-compose.yml"
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-php/install-dependencies
