version: 2.1

orbs:
  ci-caching: jobcloud/ci-caching@dev:c6fc087
  ci-php: jobcloud/ci-php@dev:05f62e9

workflows:
  php-kafka-schema-registry-client:
    jobs:
      - ci-caching/build-docker-images:
          dockerComposeFile: "./docker/docker-compose.yml"
      - ci-php/install-dependencies:
          dockerComposeFile: "./docker/docker-compose.yml"
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-caching/build-docker-images
      - ci-php/coverage:
          dockerComposeFile: "./docker/docker-compose.yml"
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-php/install-dependencies
      - ci-php/code-style:
          dockerComposeFile: "./docker/docker-compose.yml"
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-php/install-dependencies
      - ci-php/static-analysis:
          dockerComposeFile: "./docker/docker-compose.yml"
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-php/install-dependencies
      - ci-php/infection-testing:
          dockerComposeFile: "./docker/docker-compose.yml"
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-php/install-dependencies
